/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface CreateVenueDto {
  /** @nullable */
  venueName?: string | null;
  typeId?: number;
  maxCapacity?: number;
  /** @nullable */
  description?: string | null;
  /** @nullable */
  contactEmail?: string | null;
  /** @nullable */
  contactPhone?: string | null;
  /** @nullable */
  imagesUrl?: string | null;
  active?: boolean;
  /** @nullable */
  venueUrl?: string | null;
  locationId?: number;
  rows?: number;
  seatsPerRow?: number;
}
