/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export type SeatingType = typeof SeatingType[keyof typeof SeatingType];


export const SeatingType = {
  NUMBER_0: 0,
  NUMBER_1: 1,
} as const;
