/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface TimeSpan {
  ticks?: number;
  readonly days?: number;
  readonly hours?: number;
  readonly milliseconds?: number;
  readonly microseconds?: number;
  readonly nanoseconds?: number;
  readonly minutes?: number;
  readonly seconds?: number;
  readonly totalDays?: number;
  readonly totalHours?: number;
  readonly totalMilliseconds?: number;
  readonly totalMicroseconds?: number;
  readonly totalNanoseconds?: number;
  readonly totalMinutes?: number;
  readonly totalSeconds?: number;
}
