/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * Fringe API
 * API for Fringe application
 * OpenAPI spec version: v1
 */

export interface UpdateTicketTypeDto {
  /**
   * @minLength 0
   * @maxLength 100
   */
  typeName: string;
  /**
   * @minLength 0
   * @maxLength 200
   * @nullable
   */
  description?: string | null;
}
