// app/dashboard/_components/SalesChart.tsx
'use client';
import { Card, Title, Text, Stack, useMantineTheme } from '@mantine/core';
import {
    ResponsiveContainer, BarChart, CartesianGrid, XAxis,
    YAxis, Tooltip, Legend, Bar,
} from 'recharts';

interface SalesData {
    showName: string;
    totalRevenue: number;
}

interface SalesChartProps {
    data: SalesData[];
}

export function SalesChart({ data }: SalesChartProps) {
    const theme = useMantineTheme();

    const chartData = data.map(item => ({
        showName: item.showName, //
        "Total Revenue": item.totalRevenue, //
    }));

    return (
        <Card withBorder radius="md" p="lg">
            <Stack gap={0}>
                <Title order={4}>All-Time Sales Performance</Title>
                <Text c="dimmed" fz="sm">Total revenue generated by each show.</Text>
            </Stack>

            <div style={{ height: '350px', marginTop: '1.5rem' }}>
                <ResponsiveContainer width="100%" height="100%">
                    <BarChart data={chartData} margin={{ top: 5, right: 20, left: 10, bottom: 5 }}>
                        <CartesianGrid strokeDasharray="3 3" vertical={false} />
                        <XAxis dataKey="showName" tick={{ fontSize: 12 }} angle={-10} textAnchor="end" height={50} />
                        <YAxis tick={{ fontSize: 12 }} tickFormatter={(value) => `$${(Number(value) / 1000).toFixed(0)}k`} />
                        <Tooltip
                            cursor={{ fill: 'rgba(238, 239, 242, 0.5)' }}
                            contentStyle={{ borderRadius: 'var(--mantine-radius-md)', borderColor: 'var(--mantine-color-gray-3)' }}
                            formatter={(value: any) => [`$${Number(value).toLocaleString('en-US', { minimumFractionDigits: 2 })}`, 'Total Revenue']}
                        />
                        <Legend wrapperStyle={{ paddingTop: '20px' }} />
                        <Bar dataKey="Total Revenue" fill={theme.colors.blue[6]} radius={[4, 4, 0, 0]} />
                    </BarChart>
                </ResponsiveContainer>
            </div>
        </Card>
    );
}